import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { poppins, fontSans } from "@/config/fonts";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";

export const metadata: Metadata = {
  title: "Home - HobbyCue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${poppins.variable} ${fontSans.variable}`}
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${poppins.className} antialiased`}>
        <div className="min-h-screen ">
          {/* <Navbar /> */}
          <main className="max-w-screen-xxl mx-auto relative">
            {children}
            {/* <ScrollToTop /> */}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
